# Basic dependabot.yml to update gomod
version: 2
updates:
  - package-ecosystem: "gomod"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for npm updates at 9am UTC (5am EST)
      time: "10:00"
    labels:
      - "deps"
