project_name: headers-client
env:
  - DOCKERHUB_USERNAME={{ if index .Env "DOCKERHUB_USERNAME"  }}{{ .Env.DOCKERHUB_USERNAME }}{{ else }}4chainstudiopulse{{ end }}
  - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-build
    main: ./cmd/main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64



archives:
  - name_template: '{{ .ProjectName }}_{{ title .Os }}_{{ replace .Arch "amd64" "x86_64"  }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - data/**/*

release:
  disable: true

snapshot:
  name_template: "{{ incminor .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
