FROM alpine:3.17.2

# Create appuser.
ENV USER=appuser
RUN adduser ${USER} --disabled-password

USER appuser:appuser
WORKDIR /app
COPY --chown=${USER}:${USER} data data
COPY --chown=${USER}:${USER} headers-client .

ENTRYPOINT ["./headers-client"]