version: '3.8'

services:
  app:
    container_name: p2p-headers
    build: ./
    ports:
      - "8080:8080"
      - "8333:8333"
    links:
      - db
    environment:
      - DB_PREPAREDDB=true
      - DB_PREPAREDDBFILEPATH=./data/blockheaders.xz
      - HTTP_AUTHTOKEN=admin_only_afUMlv5iiDgQtj22O9n5fADeSb
      - DB_TYPE=postgres
      - DB_DSN=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    restart: unless-stopped
  db:
    image: postgres
    volumes:
      - /usr/local/var/:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
